import type {
  GitHubPullRequestComment,
  GitHubPullRequestReview,
  GitHubPullRequestReviewComment,
} from '../../github/models/github-pull-request.model';
import type { ReviewerCommentModel } from '../models/reviewer-comment.model';

export interface CollectReviewerCommentsInput {
  reviewerLogin: string;
  reviewComments: GitHubPullRequestReviewComment[];
  issueComments: GitHubPullRequestComment[];
  reviews: GitHubPullRequestReview[];
}

const AUTO_GENERATED_REVIEW_BODY_MARKERS = [
  '**Visão Geral**',
  '**Tabela de Riscos**',
  '## Resumo do Re-review',
  '## Re-review automatizada',
];

export function collectReviewerComments(
  input: CollectReviewerCommentsInput,
): ReviewerCommentModel[] {
  const { reviewerLogin, reviewComments, issueComments, reviews } = input;
  const normalizedLogin = reviewerLogin.trim().toLowerCase();

  if (!normalizedLogin) {
    return [];
  }

  const collected: ReviewerCommentModel[] = [];
  const dedupeKeys = new Set<string>();

  for (const reviewComment of reviewComments) {
    if (!matchesReviewer(reviewComment.author, normalizedLogin)) {
      continue;
    }

    const trimmedBody = reviewComment.body.trim();
    if (!trimmedBody) {
      continue;
    }

    const filePath = reviewComment.filePath?.trim() || null;
    const line = reviewComment.line ?? reviewComment.originalLine ?? null;
    const codeSnippet = reviewComment.diffHunk?.trim() || null;
    const outdated =
      reviewComment.position === null &&
      reviewComment.originalPosition !== null;

    const dedupeKey = buildDedupeKey({
      filePath,
      line,
      codeSnippet,
      body: trimmedBody,
    });

    if (dedupeKeys.has(dedupeKey)) {
      continue;
    }
    dedupeKeys.add(dedupeKey);

    collected.push({
      id: `review-comment:${reviewComment.id}`,
      source: 'review-comment',
      author: reviewComment.author,
      body: trimmedBody,
      filePath,
      line,
      codeSnippet,
      createdAt: reviewComment.createdAt,
      outdated,
    });
  }

  for (const issueComment of issueComments) {
    if (!matchesReviewer(issueComment.author, normalizedLogin)) {
      continue;
    }

    const trimmedBody = issueComment.body.trim();
    if (!trimmedBody) {
      continue;
    }
    if (looksLikeAutoGeneratedBody(trimmedBody)) {
      continue;
    }

    const dedupeKey = buildDedupeKey({
      filePath: null,
      line: null,
      codeSnippet: null,
      body: trimmedBody,
    });

    if (dedupeKeys.has(dedupeKey)) {
      continue;
    }
    dedupeKeys.add(dedupeKey);

    collected.push({
      id: `issue-comment:${issueComment.createdAt}`,
      source: 'issue-comment',
      author: issueComment.author,
      body: trimmedBody,
      filePath: null,
      line: null,
      codeSnippet: null,
      createdAt: issueComment.createdAt,
      outdated: false,
    });
  }

  for (const review of reviews) {
    if (!matchesReviewer(review.author, normalizedLogin)) {
      continue;
    }

    const trimmedBody = review.body.trim();
    if (!trimmedBody) {
      continue;
    }
    if (looksLikeAutoGeneratedBody(trimmedBody)) {
      continue;
    }

    const dedupeKey = buildDedupeKey({
      filePath: null,
      line: null,
      codeSnippet: null,
      body: trimmedBody,
    });

    if (dedupeKeys.has(dedupeKey)) {
      continue;
    }
    dedupeKeys.add(dedupeKey);

    collected.push({
      id: `review-body:${review.id}`,
      source: 'review-body',
      author: review.author,
      body: trimmedBody,
      filePath: null,
      line: null,
      codeSnippet: null,
      createdAt: review.submittedAt ?? '',
      outdated: false,
    });
  }

  return collected;
}

function matchesReviewer(author: string, normalizedLogin: string): boolean {
  return author.trim().toLowerCase() === normalizedLogin;
}

function looksLikeAutoGeneratedBody(body: string): boolean {
  return AUTO_GENERATED_REVIEW_BODY_MARKERS.some((marker) =>
    body.includes(marker),
  );
}

function buildDedupeKey(input: {
  filePath: string | null;
  line: number | null;
  codeSnippet: string | null;
  body: string;
}): string {
  const fileKey = input.filePath ?? '';
  const lineKey = input.line === null ? '' : String(input.line);
  const snippetKey = (input.codeSnippet ?? '').replace(/\s+/g, ' ').trim();
  const bodyKey = input.body.replace(/\s+/g, ' ').trim().toLowerCase();

  return `${fileKey}|${lineKey}|${snippetKey}|${bodyKey}`;
}
